/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_kursus;
import uas_crudfahri.koneksidb;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class kursus extends javax.swing.JFrame {
    
    private DefaultTableModel tblkursus;
    private String SQL;
    
    public void TampilData(){
        tblkursus = new DefaultTableModel();
        tblkursus.addColumn("Course Name");
        tblkursus.addColumn("Course Number");
        tblkursus.addColumn("Enrollment");
        tblkursus.addColumn("Start Date");
        tblkursus.addColumn("End Date");
        jTable_course.setModel(tblkursus);
        Connection conn = koneksidb.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from daftarkursus";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()){
                tblkursus.addRow(new Object[]{
                    res.getString("course_name"),
                    res.getString("course_number"),
                    res.getString("enrollment"),
                    res.getString("start_date"),
                    res.getString("end_date")
                 });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Creates new form kursus
     */
    public kursus() {
        initComponents();
        this.TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField_course_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_course_number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_enrollment = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_start_date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_end_date = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_course = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DAFTAR JENIS KURSUS");

        jTextField_course_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_course_nameActionPerformed(evt);
            }
        });

        jLabel2.setText("Course Name");

        jLabel3.setText("Course Number");

        jTextField_course_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_course_numberActionPerformed(evt);
            }
        });

        jLabel4.setText("Enrollment");

        jLabel5.setText("Start Date");

        jLabel6.setText("End Date");

        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_delete.setText("Delete");

        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jTable_course.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "course_name", "course_number", "enrollment", "start_date", "end_date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_courseMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_course);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_course_name))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jButton_add))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_course_number)
                                            .addComponent(jTextField_enrollment)
                                            .addComponent(jTextField_start_date)
                                            .addComponent(jTextField_end_date)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jButton_delete)
                                        .addGap(40, 40, 40)
                                        .addComponent(jButton_update)
                                        .addGap(0, 55, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_course_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_course_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_enrollment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_start_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_end_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add)
                    .addComponent(jButton_delete)
                    .addComponent(jButton_update))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_course_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_course_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_course_nameActionPerformed

    private void jTextField_course_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_course_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_course_numberActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        try {
                Connection conn = koneksidb.getConnection();
                PreparedStatement stmt = conn.prepareStatement("insert into daftarkursus(course_name, course_number, enrollment, start_date, end_date) values(?,?,?,?,?)");
                stmt.setString(1, jTextField_course_name.getText());
                stmt.setString(2, jTextField_course_number.getText());
                stmt.setString(3, jTextField_enrollment.getText());
                stmt.setString(4, jTextField_start_date.getText());
                stmt.setString(5, jTextField_end_date.getText());
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil ditambah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jTable_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_courseMouseClicked
        // TODO add your handling code here:
        int baris = jTable_course.getSelectedRow();
        jTextField_course_name.setText(tblkursus.getValueAt(baris, 0).toString());
        jTextField_course_number.setText(tblkursus.getValueAt(baris, 1).toString());
        jTextField_enrollment.setText(tblkursus.getValueAt(baris, 2).toString());
        jTextField_start_date.setText(tblkursus.getValueAt(baris, 3).toString());
        jTextField_end_date.setText(tblkursus.getValueAt(baris, 4).toString());
    }//GEN-LAST:event_jTable_courseMouseClicked

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        try {
        Connection conn = koneksidb.getConnection();
        PreparedStatement stmt = conn.prepareStatement("update daftarkursus set course_name=?, course_number=?, enrollment=?, start_date=?, end_date=?");
        stmt.setString(1, jTextField_course_name.getText());
            stmt.setString(2, jTextField_course_number.getText());
            stmt.setString(3, jTextField_enrollment.getText());
            stmt.setString(4, jTextField_start_date.getText());
            stmt.setString(5, jTextField_end_date.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        }catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kursus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kursus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kursus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kursus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kursus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_course;
    private javax.swing.JTextField jTextField_course_name;
    private javax.swing.JTextField jTextField_course_number;
    private javax.swing.JTextField jTextField_end_date;
    private javax.swing.JTextField jTextField_enrollment;
    private javax.swing.JTextField jTextField_start_date;
    // End of variables declaration//GEN-END:variables
}
